# Example docker-compose.yml for local development dependencies
# Run with: docker-compose up -d
version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: test-db
    env_file: .env # Load environment variables from .env file
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d test_results_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3.12-management-alpine # Use management image for UI
    container_name: test-queue
    env_file: .env # Load environment variables from .env file
    ports:
      - "5672:5672"   # AMQP port
      - "15672:15672" # Management UI port
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:latest
    container_name: test-storage
    env_file: .env # Load environment variables from .env file
    ports:
      - "9000:9000" # API port
      - "9001:9001" # Console UI port
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 2s
      retries: 5

volumes:
  postgres_data:
  minio_data:
